### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by jneen** [fstarred/xrns2xmod#6]
The docs merely specify installing Mono and then finding an *.exe file that does not seem to exist. `xbuild` fails because it can't find `Xrns2XMod/ModUtils.cs`. I feel like I'm probably missing something very basic.

**Comment by fstarred** [comment]
As stated in Issue #3 , it's enough to rename _MODUtils.cs_ to _ModUtils.cs_.
I have updated source in order to fix this inconvenient, and then I launched succesfully the xbuild, launching a command like this:

`xbuild Xrns2XModCmd/Xrns2XModCmd.csproj /t:Rebuild /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=portable /p:Platform="x64" /p:OutputPath=<output_path>`

I have also tried with Xrns2XModUI, but I receive a compilation error because xbuild can't find a component that belongs from the external library ServiceUpdater.dll (while on Windows there are no issues).

So said, the _Xrns2XModShell.exe_ is already present on all the latest release bundles so compiling the project it's not required at all.

**UPDATE**
After fixing reference to _ServiceUpdater.dll_, I was able to compile also Xrns2XModUI with xbuild

**NOTICE**
Remember to replace bass dll with libbassflac.so, libbassmix.so and libbass.so for Linux

**Comment by jneen** [comment]
I see, thank you!
