### ISSUE TITLE
InflaterInputStream Position not supported

### ISSUE THREAD

**Issue by dahlgrenmartin** [fstarred/xrns2xmod#7]
Hi! 

I get this error with Renoise 3.1.1-x64 when trying to convert songs (example Demo by Dblue).

Ramping sample volume to value 4
Processing instrument 15/24, sample 1/9
Processing instrument 15/24, sample 2/9
Processing instrument 15/24, sample 3/9
Processing instrument 15/24, sample 4/9
Processing instrument 15/24, sample 5/9
Processing instrument 15/24, sample 6/9
Processing instrument 15/24, sample 7/9
Processing instrument 15/24, sample 8/9
Processing instrument 15/24, sample 9/9
InflaterInputStream Position not supportedI

Thanks,
Martin.

**Comment by fstarred** [comment]
From a rational point of view, your intent to use Xrns2XMod with a song like Demo by Dblue makes no sense at all, simply because you are trying to convert a third generation module with DSP, effects and more else with something that has nothing to do with that...

By the way your issue brought me realizing that even WAV format was never supported, so with the today release several audio format (WAV, OGG) were included.

PS
If you want to test Xrns2XMod features, you can open the xrns examples included in the package (there is also a navigation menu on the Xrns2XMod tool to ease this operation)
